#!/usr/bin/env bash

set -euo pipefail

# Replace version in flake.nix
# If the pattern is not found, exit with code 128
# If the version is not set, exit with code 1
# shellcheck disable=SC2016
sed -r '/(baseVersion = ")[^"]+(";)/,${s//\1'"${1:?Set version}"'\2/;b};$q128' flake.nix

# Run nix-update to update vendorHash
nix run github:Mic92/nix-update -- --flake gke-kubeconfiger --version=skip
