---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  # - "@semantic-release/release-notes-generator"
  # - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: .github/scripts/prepare ${nextRelease.version}
  # - "@semantic-release/git"
tagFormat: "${version}"
