---
name: Lint Job

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: "1.22"
          cache: false
      - name: Install gofumpt
        uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b # v1.11.0
        with:
          repo: mvdan/gofumpt
          tag: v0.5.0
          cache: enable
          extension-matching: nah
          rename-to: gofumpt
          chmod: 0700
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - name: Check code formatting
        run: |
          set -euo pipefail
          gofumpt -l $( \
              git diff-tree -r --no-commit-id --name-only --diff-filter=ACMRT \
                "origin/$GITHUB_BASE_REF..origin/$GITHUB_HEAD_REF" \
              | grep '\.go$' \
            ) \
            | tee /dev/stderr \
            | test $(wc -l) -eq 0
      - uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4
